name: Trigger reusable workflow in a public repo

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  env1: "An environment variable in caller workflow in ${{github.event.repository.name}}"
jobs:
  run-reuse-workflow:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iduses
    # {owner}/{repo}/.github/workflows/{filename}@{ref}
    uses: softcat477/reuse-workflow/.github/workflows/reuse-workflow.yml@v1.0.0
    with:
      input1: "This-is-input-1-from-caller-workflow-in-${{github.event.repository.name}}"
    secrets:
      secret1: ${{ secrets.secret0 }}

  show-output-from-reuse-workflow:
    runs-on: ubuntu-latest
    needs: run-reuse-workflow
    steps:
      - name: Print single-line output
        run: echo '${{needs.run-reuse-workflow.outputs.reuse-workflow-out1}}'
      - name: Print multi-line output
        run: echo '${{needs.run-reuse-workflow.outputs.reuse-workflow-out2}}'