name: "Bad composite actions trying to access secrets in the caller workflow"

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CALLER_ENV: "---"

jobs:
  use-failed-composite-action:
    name: Use Composite Action in the same Repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: First step is just a warm greeting
        run: echo "Hi"

      - name: Access secrets in the caller workflow
        run: echo "SECRET0 is:${{secrets.SECRET0}}"

      # This step throws error. It tries to access secrets in the caller workflow. It's not going to work.
      # uses: {owner}/{repo}/{path}@{ref}
      - name: Use composite action
        id: composite-action
        uses: softcat477/composite-action/.github/bad-composite-action@v1.0.0
        env:
          ASSIGNED_ENV: "---"
        with:
          input1: "An input assigned to composite actions"